In [1]:
a = [1,2,3]
a[0]

1

In [2]:
a

[1, 2, 3]

In [3]:
import torch
a = torch.ones(3)

In [4]:
a

tensor([1., 1., 1.])

In [5]:
a[1]

tensor(1.)

In [6]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [7]:
points = torch.tensor([1,4,2,1,3,5])
points

tensor([1, 4, 2, 1, 3, 5])

In [9]:
float(points[0]),float(points[1])

(1.0, 4.0)

In [4]:
points = torch.tensor([[1.0,4.0],[2.0,1.0],[3.0,5.]])
points

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [15]:
points.shape

torch.Size([3, 2])

In [16]:
points[0,1]

tensor(4.)

In [5]:
points.storage()

 1.0
 4.0
 2.0
 1.0
 3.0
 5.0
[torch.FloatStorage of size 6]

In [10]:
points_storage = points.storage()
points_storage[0]

3.700000047683716

In [12]:
points_storage[0] = 3.7
points

tensor([[3.7000, 4.0000],
        [2.0000, 1.0000],
        [3.0000, 5.0000]])

# Size, storage offset, and strides

In [14]:
second_point = points[1]
second_point.storage_offset()

2

In [16]:
second_point.size()

torch.Size([2])

In [18]:
points.stride()

(2, 1)

In [20]:
third_point = points[2]
third_point[0] = 10.0
points

tensor([[ 3.7000,  4.0000],
        [ 2.0000,  1.0000],
        [10.0000,  5.0000]])

In [21]:
third_point = points[2].clone()
third_point = 4.2
points

tensor([[ 3.7000,  4.0000],
        [ 2.0000,  1.0000],
        [10.0000,  5.0000]])

In [22]:
points_t = points.t()
points_t

tensor([[ 3.7000,  2.0000, 10.0000],
        [ 4.0000,  1.0000,  5.0000]])

In [23]:
id(points.storage()) == id(points_t.storage())

True

In [24]:
some_tensor = torch.ones(3,8,5)
some_tensor_t = some_tensor.transpose(0,2)
some_tensor.shape

torch.Size([3, 8, 5])

In [25]:
some_tensor_t.shape

torch.Size([5, 8, 3])

In [26]:
some_tensor.stride()
# 第一个数的步长stride = 5*8，即第一行第一个数字加上40后会换到第二行的第一个数字

(40, 5, 1)

In [28]:
some_tensor_t.stride()

(1, 5, 40)

In [29]:
points

tensor([[ 3.7000,  4.0000],
        [ 2.0000,  1.0000],
        [10.0000,  5.0000]])

In [33]:
with open ('points.t', 'wb') as f:
    torch.save(points, f)

In [34]:
points_ld = torch.load('points.t')

In [35]:
points_ld

tensor([[ 3.7000,  4.0000],
        [ 2.0000,  1.0000],
        [10.0000,  5.0000]])

In [37]:
a = torch.ones(3,2)

In [38]:
a_t = torch.transpose(a,0,1)
a_t

tensor([[1., 1., 1.],
        [1., 1., 1.]])

# exercise 1 

In [41]:
list = range(9)
list

range(0, 9)

In [42]:
import numpy as np
list = np.arange(9)

In [43]:
a = torch.from_numpy(list)
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [51]:
print(a.shape, a.size(), a.stride(), a[2].storage_offset())

torch.Size([9]) torch.Size([9]) (1,) 2


# exercise 2 

In [70]:
b = a.view(-1, 3)
b

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [54]:
b[1,1]

tensor(4)

# exercise 3 

In [59]:
c = b[1:, 1:,]
print(c.size(), c.stride(), c.storage_offset())

torch.Size([2, 2]) (3, 1) 4


In [61]:
d = b[1:, 1:].clone()
print (d.size(), d.stride(), d.storage_offset())

torch.Size([2, 2]) (2, 1) 0


# exercise 4